#!/usr/bin/env bash
shopt -s nullglob

case "$1" in
    debug)
        docker run \
            --env-file "$VG_ENV_FILE" \
            --interactive \
            --tty \
            --net=host \
            --volume=$VG_APP_DIR:/usr/src/app \
            --name=vg_app_debug \
            vg_app python wsgi.py
        docker stop vg_app_debug &> /dev/null
        docker rm vg_app_debug &> /dev/null
        exit $VG_VALID_EXIT
        ;;
    help)
        echo "    app debug - Run the Flask debug server"
        ;;
    *)
        exit $VG_NOT_IMPLEMENTED_EXIT
        ;;
esac
