#!/usr/bin/env bash
set -eo pipefail
shopt -s nullglob

case "$1" in
    shell)
        docker run \
            --env-file "$VG_ENV_FILE" \
            --interactive \
            --tty \
            --rm \
            --net=host \
            --name=vg_app_shell \
            --volume="$VG_APP_DIR":/usr/src/app \
            vg_app bash
        docker stop vg_app_shell &> /dev/null
        docker rm vg_app_shell &> /dev/null
        exit $VG_VALID_EXIT
        ;;
    run)
        docker run \
            --env-file "$VG_ENV_FILE" \
            --interactive \
            --tty \
            --net=host \
            --volume=$VG_APP_DIR:/usr/src/app \
            --name=vg_app_run \
            vg_app
        docker stop vg_app_run &> /dev/null
        docker rm vg_app_run &> /dev/null
        exit $VG_VALID_EXIT
        ;;
    help)
        echo "    app shell (override) - Open a shell, mount the APP_DIR"
        ;;
    *)
        exit $VG_NOT_IMPLEMENTED_EXIT
        ;;
esac
