#!/usr/bin/env bash
shopt -s nullglob

case "$1" in
    '')
        heroku scale web=1 --app distorteddecade
        heroku maintenance:off --app distorteddecade
        exit $VG_VALID_EXIT
        ;;
    *)
        exit $VG_NOT_IMPLEMENTED_EXIT
        ;;
esac