#!/usr/bin/env bash
shopt -s nullglob

case "$1" in
    '')
        heroku maintenance:on --app distorteddecade
        heroku scale web=0 --app distorteddecade
        heroku pg:backups capture --app distorteddecade
        exit $VG_VALID_EXIT
        ;;
    *)
        exit $VG_NOT_IMPLEMENTED_EXIT
        ;;
esac