"""added embed

Revision ID: 2dec83081e82
Revises: 2e10ba70c8b6
Create Date: 2015-06-06 16:14:46.863532

"""

# revision identifiers, used by Alembic.
revision = '2dec83081e82'
down_revision = '2e10ba70c8b6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embed',
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('eid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embed')
    ### end Alembic commands ###
