"""removed User email

Revision ID: 2e10ba70c8b6
Revises: 2a282664052a
Create Date: 2015-06-06 15:40:57.427462

"""

# revision identifiers, used by Alembic.
revision = '2e10ba70c8b6'
down_revision = '2a282664052a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
