#!/usr/bin/env bash
set -eo pipefail
shopt -s nullglob

case "$1" in
    demo)
        here=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
        case "$2" in
            save)
                vantage pg dump > "$here/demo.dump"
                exit $VG_VALID_EXIT
                ;;
            '')
                vantage pg restore "$here/demo.dump"
                exit $VG_VALID_EXIT
                ;;
            *)
                exit $VG_NOT_IMPLEMENTED_EXIT
                ;;
        esac
        ;;
    help)
        echo "    pg demo - Create a new DB, fill it with demo data"
        echo "    pg demo save - Save DATABASE_URL as future demo data"
        ;;
    *)
        exit $VG_NOT_IMPLEMENTED_EXIT
        ;;
esac
